<a href="https://colab.research.google.com/github/kotharisanjana/CMPE258_DeepLearning_Spring2023/blob/main/Assignment_2/2c/Demo_Tensoflow_Pytorch_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Imports
import numpy as np
from sklearn import preprocessing

import tensorflow as tf
import torch
import tensorflow._api.v2.compat.v1 as v1
v1.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


### Tensorflow

In [16]:
sample_data = tf.constant([1,2,3,4,5,6,7])
print('Sample data:', sample_data)

Sample data: Tensor("Const_3:0", shape=(7,), dtype=int32)


In [17]:
# Broadcast
broadcast_data = tf.broadcast_to(sample_data, [3, 7])
print('This is the data after broadcasting:',broadcast_data)

This is the data after broadcasting: Tensor("BroadcastTo_1:0", shape=(3, 7), dtype=int32)


In [18]:
# Tensor with float values
rank_1_tensor = tf.constant([1.5, 2.5, 3.5, 4.5])
print(rank_1_tensor)

Tensor("Const_4:0", shape=(4,), dtype=float32)


In [19]:
# Tensor with three axis
rank_2_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_2_tensor)

Tensor("Const_5:0", shape=(3, 2, 5), dtype=int32)


In [20]:
# Smaller tensors are 'stretched' automatically to fit larger tensors when running combined operations on them.
x = tf.constant([1,2,3])
y = tf.constant(2)
z = tf.constant([5,6,7])

print(tf.multiply(x, 2))
print(x * y)
print(x * z)

Tensor("Mul:0", shape=(3,), dtype=int32)
Tensor("mul_1:0", shape=(3,), dtype=int32)
Tensor("mul_2:0", shape=(3,), dtype=int32)


In [21]:
# Same operations without broadcasting
x_stretch = tf.constant([[1, 1, 1, 1],
                         [2, 2, 2, 2],
                         [3, 3, 3, 3]])

y_stretch = tf.constant([[1, 2, 3, 4],
                         [1, 2, 3, 4],
                         [1, 2, 3, 4]])

print(x_stretch * y_stretch) 

Tensor("mul_3:0", shape=(3, 4), dtype=int32)


In [22]:
# A tensor with variable numbers of elements along some axis is called 'ragged'. 
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

tf.RaggedTensor(values=Tensor("RaggedConstant/values:0", shape=(10,), dtype=int32), row_splits=Tensor("RaggedConstant/Const:0", shape=(5,), dtype=int64))


In [23]:
# Sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor)

# Convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=Tensor("SparseTensor/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor/dense_shape:0", shape=(2,), dtype=int64))
Tensor("SparseToDense:0", shape=(3, 4), dtype=int32)


In [24]:
# Scalar string tensor
scalar_string_tensor = tf.constant('Hello World')
print(scalar_string_tensor)

Tensor("Const_11:0", shape=(), dtype=string)


In [25]:
tensor_of_strings = tf.constant(['Hello World',
                                 'Trying tensorflow',
                                 'CMPE258 Deep Learning'])

print(tensor_of_strings)

Tensor("Const_12:0", shape=(3,), dtype=string)


In [26]:
# Split a string into a set of tensors
print(tf.strings.split(scalar_string_tensor, sep=' '))

Tensor("StringSplit/RaggedGetItem/strided_slice_5:0", shape=(?,), dtype=string)


In [27]:
# Convert string to a number
text = tf.constant('1 10 100')
print(tf.strings.to_number(tf.strings.split(text, ' ')))

Tensor("StringToNumber:0", shape=(?,), dtype=float32)


In [28]:
# Converting string to bytes and then to ascii values
byte_strings = tf.strings.bytes_split(tf.constant('Hello'))
byte_ints = tf.io.decode_raw(tf.constant('Hello'), tf.uint8)
print('Byte strings:', byte_strings)
print('Bytes:', byte_ints)

Byte strings: Tensor("StringsByteSplit/RaggedGetItem/strided_slice_5:0", shape=(?,), dtype=string)
Bytes: Tensor("DecodeRaw:0", shape=(?,), dtype=uint8)


In [29]:
# Splitting strings as unicode and then decode it
unicode_bytes = tf.constant('アヒル 🦆')
unicode_char_bytes = tf.strings.unicode_split(unicode_bytes, 'UTF-8')
unicode_values = tf.strings.unicode_decode(unicode_bytes, 'UTF-8')

print('\nUnicode bytes:', unicode_bytes)
print('\nUnicode chars:', unicode_char_bytes)
print('\nUnicode values:', unicode_values)


Unicode bytes: Tensor("Const_16:0", shape=(), dtype=string)

Unicode chars: Tensor("UnicodeSplit/UnicodeEncode/UnicodeEncode/UnicodeEncode:0", shape=(5,), dtype=string)

Unicode values: Tensor("UnicodeDecode/UnicodeDecode:1", shape=(?,), dtype=int32)


In [30]:
my_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])

# Create a and b; they will have the same name but will be backed by different tensors.
a = tf.Variable(my_tensor, name='Mark')
# A new variable with the same name, but different value
b = tf.Variable(my_tensor + 1, name='Mark')

# These are elementwise-unequal, despite having the same name
print(a == b)

False


Operations in Pytorch

### Pytorch

In [31]:
tensor1 = torch.tensor([[1, 2], [4, 3]])
tensor2 = torch.tensor([[6, 2]])
tensor3 = torch.tensor([[5], [2]])
tensor4 = torch.tensor([7])

print(tensor1.shape)
print(tensor2.shape)
print(tensor3.shape)
print(tensor4.shape)

print(tensor1 + tensor2)
print(tensor1 + tensor3)
print(tensor2 + tensor3)
print(tensor1 + tensor4)

torch.Size([2, 2])
torch.Size([1, 2])
torch.Size([2, 1])
torch.Size([1])
tensor([[ 7,  4],
        [10,  5]])
tensor([[6, 7],
        [6, 5]])
tensor([[11,  7],
        [ 8,  4]])
tensor([[ 8,  9],
        [11, 10]])


In [32]:
a = torch.randn(1, 100) 

nt = torch.nested.nested_tensor([a, a], dtype=torch.float32)

torch.stack(nt.unbind()).size()
torch.Size([2, 20, 128])
torch.stack([a, a]).size()
torch.Size([2, 20, 128])
torch.equal(torch.stack(nt.unbind()), torch.stack([a, a]))

True

In [33]:
a = torch.tensor([[0, 2.], [3, 0]])
a.to_sparse()

tensor(indices=tensor([[0, 1],
                       [1, 0]]),
       values=tensor([2., 3.]),
       size=(2, 2), nnz=2, layout=torch.sparse_coo)

In [34]:
t = torch.tensor([[[1, 0], [2, 3]], [[4, 0], [5, 6]]])
print(t.dim())
t.to_sparse_csr()

3


tensor(crow_indices=tensor([[0, 1, 3],
                            [0, 1, 3]]),
       col_indices=tensor([[0, 0, 1],
                           [0, 0, 1]]),
       values=tensor([[1, 2, 3],
                      [4, 5, 6]]), size=(2, 2, 2), nnz=3,
       layout=torch.sparse_csr)

In [35]:
imgs = torch.randn(1, 2, 2, 3 , names=('N', 'C', 'H', 'W'))
imgs.names
renamed_imgs = imgs.rename(H='height', W='width')
renamed_imgs.names

('N', 'C', 'height', 'width')

In [36]:
x = torch.randn(3, names=('X',))
y = torch.randn(3)
z = torch.randn(3, names=('Z',))

In [37]:
(x + y).names
(x + x).names

('X',)

In [38]:
labels = ['cat', 'dog', 'mouse', 'elephant', 'pandas']
le = preprocessing.LabelEncoder()
targets = le.fit_transform(labels)
targets = torch.as_tensor(targets)
print(targets)

tensor([0, 1, 3, 2, 4])


### Linear Search using tensorflow

In [41]:
class LinearSearch():
  def __init__(self, array, x):
      self.x = tf.constant(x)
      self.array = tf.constant(array)
      self.length = len(array)
      self.graph = tf.while_loop(self.cond, self.body, [0, False])

  def run(self):
      with tf.compat.v1.Session() as sess:
          return sess.run(self.graph)

  def cond(self, i, is_found):
      return tf.logical_and(tf.less(i, self.length), tf.logical_not(is_found))

  def body(self, i, is_found):
      return tf.cond(tf.equal(self.array[i], self.x), lambda: (i, True), lambda: (tf.add(i, 1), False))

if __name__ == '__main__':
    array, x = [15, 20, 45, 33, 84, 100, 12], 100
    search = LinearSearch(array, x)
    ix, is_found = search.run()
    print('Array :', array)
    print('Number to search :', x)
    if is_found:
        print('{} is at index {}.'.format(x, ix))
    else:
        print('Not found.')

Array : [15, 20, 45, 33, 84, 100, 12]
Number to search : 100
100 is at index 5.


### Binary Search using tensorflow

In [42]:
class BinarySearch():
  def __init__(self, array, x):
    self.array = tf.constant(array)
    self.x = tf.constant(x)
    self.loop = tf.while_loop(self.cond, self.body, [-1, False, 0, len(array), -1])

  def run(self):
    with tf.compat.v1.Session() as sess:
        return sess.run(self.loop)

  def cond(self, x, is_found, left, right, mid):
    return tf.logical_and(tf.less_equal(left, right), tf.logical_not(is_found))

  def body(self, x, is_found, left, right, mid):
    mid = tf.cast(tf.divide(tf.add(left, right), 2),tf.int32)
    return tf.cond(tf.equal(self.array[mid], self.x),
                lambda: (self.array[mid], True, left, right, mid),
                lambda: tf.cond(tf.less(self.array[mid], self.x),
                            lambda: (-1, False, tf.add(mid, 1), right, mid),
                            lambda: (-1, False, left, tf.subtract(mid, 1), mid)))

if __name__ == '__main__':
  array = sorted([10, 30, 52, 74, 84])
  x = 52
  search = BinarySearch(array, x)
  xx, is_found, l, r, m = search.run()

  print('Array :', array)
  print('Number to search :', x)
  if is_found:
      print('{} is at index {}.'.format(xx, m))
  else:
      print('Not found.')

Array : [10, 30, 52, 74, 84]
Number to search : 52
52 is at index 2.


### Insertion sort using tensorflow

In [46]:
class InsertionSort():
    def __init__(self, array):
      self.i = tf.constant(1)
      self.j = tf.constant(len(array)-1)
      self.array = tf.Variable(array, trainable=False)
      self.length = len(array)

      cond = lambda i, j, _: tf.less(i-1, self.length-1)
      self.graph = tf.while_loop(cond, self.outer_loop, loop_vars=[self.i, self.j, self.array],
              shape_invariants=[self.i.get_shape(), self.j.get_shape(), tf.TensorShape(self.length)],
              parallel_iterations=1)

    def run(self):
      with tf.compat.v1.Session() as sess:
          tf.compat.v1.disable_eager_execution()
          tf.compat.v1.global_variables_initializer().run()
          return sess.run(self.graph)

    def outer_loop(self, i, j, _):
      j = i
      cond = lambda i, j, array: tf.logical_and(tf.greater(j,0), tf.greater(array[j-1], array[j]))

      loop = tf.while_loop(cond, self.inner_loop, loop_vars=[i, j, self.array],
                  shape_invariants=[i.get_shape(), j.get_shape(), tf.TensorShape(self.length)],
                  parallel_iterations=1,
                  back_prop=False)
      return tf.add(i, 1), loop[1], loop[2]

    def inner_loop(self, i, j, _):
      return i, tf.subtract(j, 1), tf.compat.v1.scatter_nd_update(self.array, [[j-1],[j]], [self.array[j],self.array[j-1]])


with tf.compat.v1.Session() as sess:
    x = np.array([1,7,38,0,10,9,3])
    print(InsertionSort(x).run()[2])

[ 0  1  3  7  9 10 38]
